### ISSUE TITLE
User must understand why the displayed trees match the filter criteria

### ISSUE THREAD

**Issue by DaEgi01** [TPBCS/ForestBrush#10]
Currently the user only sees the LocalizedName of the tree in the BrushEdit section. 
Since the search goes over LocalizedName, FileName, Description etc. there are many cases, when its unclear to the user why an item actually matches the filter criteria.

A potential solution is to show all the search relevant data in a tooltip when the mouse hovers over a tree in the list.

**Comment by taibenvenuti** [comment]
I removed the description matching.
Added information relative to available filters to tooltips so I think this issue is solved.
Thoughts?
Leaving open for now.

**Comment by DaEgi01** [comment]
tooltip should be fine ... its strange but its ok.
