### ISSUE TITLE
German locale: some corrections in typing and grammar

### ISSUE THREAD

**Issue by Fungopus** [TPBCS/ForestBrush#15]
Hi,
thx for the awesome mod.
I found some typing mistakes and wanted to help to fix them:

    <Translation ID="FOREST-BRUSH-TOGGLE-EDIT" String="Baumliste anzeigen/verstecken" />

    <Translation ID="FOREST-BRUSH-TOGGLE-OPTIONS" String="Pinseloptionen anzeigen/verstecken" />

    <Translation ID="FOREST-BRUSH-BRUSH-OPTIONS-OVERLAYCOLOR" String="Pinselfarbe" />

    <Translation ID="FOREST-BRUSH-TUTORIAL" String="
Danke dafür, dass du die Wald Pinsel Mod abonniert hast.&#10;&#10;
Klicke auf die Werkzeugtaste um Bäume für deinen Pinsel auszuwählen.&#10;
Nutze die Kontrollkästchen, um dem Pinsel Bäume hinzuzufügen oder zu entfernen.&#10;
Strg + Klick auf ein Kontrollkästchen um alle Bäume auszuwählen oder die Auswahl aufzuheben.&#10;&#10;
Du kannst soviele verschiedene Pinsel haben wie du magst, klicke auf die Plustaste um weitere Pinsel zu erstellen.&#10;&#10;
Nutze das Suchfeld um bestimmte Bäume zu finden.&#10;&#10;
Klicke auf die Zahnradtaste um die Pinseleinstellungen zu editieren.&#10;
Hier kannst du die Größe, Stärke und Dichte deines Pinsels setzen.&#10;
Besuche die Workshop Seite für eine ausführliche Anleitung." />

Greetings

**Comment by DaEgi01** [comment]
Danke schön :)
Wird umgehend aufgenommen.

**Comment by DaEgi01** [comment]
https://github.com/TPBCS/ForestBrush/pull/16/commits/17394bbf8b34fa6369431aabbd06bca1c62d2161
should be in today once TPB is back from work :)

**Comment by taibenvenuti** [comment]
Thanks! :)
