### ISSUE TITLE
Compatibility with Resize It!

### ISSUE THREAD

**Issue by DaEgi01** [TPBCS/ForestBrush#17]
Reported by Skignovilous in the workshop comments:
1) If you use a mod like Resize It! (i.e. a mod that changes how many items you can see in the toolbar category), depending on how many lines you choose to show, upon clicking on the Forest Brush icon, you won't be able to see the panel on the screen. (I mean that the panel gets "pushed" up on the screen so you can't see it/use it. You also can't reach the part of the panel that you can click and drag.)

**Comment by taibenvenuti** [comment]
Possibly fixed with last push. Need confirmation before closing.

**Comment by taibenvenuti** [comment]
Fixed.
