### ISSUE TITLE
Make the whole panel draggable maybe

### ISSUE THREAD

**Issue by DaEgi01** [TPBCS/ForestBrush#44]
hadhardest suggested to make the whole panel draggable instead of only the top part.
the reason was that the panel top part was pushed up out of the screen for him/her due to being to large with all panels enabled.

**Comment by DaEgi01** [comment]
not really necessary i think. the panel with all sub-panels opened still fits on 1366*768 with enough horizontal pixels left.
so I wouldn't do it, just fix the bug that lead to the suggestion in the first place.

**Comment by taibenvenuti** [comment]
Fixed bug. Closing.
